version: "3.3"
services:
#  app:
#    container_name: ecommerce-app
#    image: r0m41k96/ecommerce-app
#    build: .
#    ports:
#    - "8085:8085"
#    depends_on:
#      - db
  db:
    image: postgres
    ports:
    - "5432:5432"
    volumes:
    - /d/e-commerce-data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ugolek
  jms-broker:
    image: rmohr/activemq
    ports:
    - "61616:61616"
    - "8161:8161"
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=activemq
      - ACTIVEMQ_ADMIN_PASSWORD=activemq

