version: "3.3"
services:
  app:
    container_name: ecommerce-app
    image: r0m41k96/ecommerce-app
    build: .
    ports:
    - "8085:8085"
    depends_on:
      - db
  db:
    image: postgres
    ports:
    - "5432:5432"
    volumes:
    - /d/e-commerce-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ugolek

